# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Enlivora"
client_id = "" # To be filled by user
application_url = "https://enlivora.ngrok-free.app" # Example ngrok URL
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "" # To be filled by user

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_orders,read_orders"

[auth]
redirect_urls = [
  "https://enlivora.ngrok-free.app/auth/callback",
  "https://enlivora.ngrok-free.app/auth/shopify/callback"
]

[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "https://api.enlivora.com/webhooks/orders/paid"

[pos]
embedded = false
