[package]
name = "enlivora_contracts"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.8.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.20.0" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.50.0" }

[[target.starknet-contract]]
sierra = true
casm = true
